# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CnSlIPKv2tzCZjW7R2ALiZN3gikrxOJn
"""

#insertion sorting : card sorting
class Var:
  Epoches=100
  temp=0



def Sorting(InputArr):
  #print(CheckIfSmallerThanRight(1,0))
  for epoches in range(0,Var.Epoches):
    for Loop in range(1,len(InputArr)):

      Next=0
      Previous=0
      Current=0
      Next=Loop+1
      Previous=Loop-1
      Current=Loop
      #ALGO
      Var.temp=InputArr[Current]
      if InputArr[Previous] > InputArr[Current]:
        InputArr[Current]= InputArr[Previous]
        InputArr[Previous]=Var.temp


  print(InputArr)





    

if __name__=="__main__":
  Sorting([12,16,8,5,4,9,3])